### PR TITLE
Update .php-cs-fixer.php

### PR DESCRIPTION
**Pull request by szepeviktor**
Statements without parentheses.

https://cs.symfony.com/doc/rules/control_structure/include.html

@otsch

### CODE REVIEW

**Comment by szepeviktor** [comment]
image

**Comment by otsch** [comment]
Why? Just to change something? Sorry, I'll close it.

**Comment by szepeviktor** [comment]
I've seen `include( ... )` in the source code.

**Comment by szepeviktor** [comment]
It is not a function.

**Pull request closed without merging**
